export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_USER_START = 'SET_AUTH_USER_START';
export const SET_AUTH_USER_SUCCESS = 'SET_AUTH_USER_SUCCESS';
export const SET_AUTH_USER_ERROR = 'SET_AUTH_USER_ERROR';
export const SET_AUTH_USER_VALIDATION_ERROR = 'SET_AUTH_USER_VALIDATION_ERROR';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
